# Generated by Django 4.0.5 on 2022-06-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='post_photos/default_user.jpg', upload_to='post_photos'),
        ),
    ]
