# Generated by Django 4.0.5 on 2022-06-29 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0012_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ratio',
            field=models.ManyToManyField(blank=True, related_name='ratio', to=settings.AUTH_USER_MODEL),
        ),
    ]
